ci:
  collect:
    numberOfRuns: 3
  assert:
    preset: "lighthouse:no-pwa"
    assertions:
      categories:performance:
        - warn
        - minScore: 0.95
      categories:accessibility:
        - error
        - minScore: 1
      categories:seo:
        - error
        - minScore: 0.95
  upload:
    target: filesystem
    outputDir: lhci_reports